### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by tmniederMV** [daveleroy/sublime_debugger#206] opened 2023-02-03 18:45 UTC
I am getting this error when opening sublime text 4.  I am fairly sure it happened after updating my packages.
I have tried uninstalling sublime text 4 and all packages and re-installing but am still getting the same error.

It is causing the debugger to not work properly.

Debugger: [startup]
error: Error loading syntax file "Packages\Debugger\contributes/Syntax/DebuggerConsole.sublime-syntax": Unable to read Packages\Debugger\contributes/Syntax/DebuggerConsole.sublime-syntax
Debugger: ProjectConfiguration.reload

**Comment by LDAP** [comment] 2023-02-04 09:31
Duplicate of #201

**Comment by daveleroy** [comment] 2023-02-04 22:19
Pretty sure this is fixed see #201

**Closed by daveleroy** 2023-02-04 22:19 UTC
